name: $name
version: $version
main: net.gamershub.kitpvp.KitPvpPlugin
description: $description
load: POSTWORLD
authors:
  - Chaosdave34, Muawag, palul
api-version: "$apiVersion"
commands:
  loop:
    description: Loop command
    usage: /<command> <amount> <period> <command>
    permission: kitpvp.loop
  custom_item:
    description: Give yourself a custom item
    usage: /<command> <item_id> <amount>
  generate_spawn:
    description: Generates the spawn centered at coordinates 0, 100, 0
    usage: /<command>
  set_game_state:
    description: Sets your game state
    usage: /<command> <game_state>
  spawn:
    description: Teleports you back to the spawn
    usage: /<command>
  add_experience:
    description: Adds experience to the player
    usage: /<command> <player> <amount>
  test_companion:
    description: Test companions
    usage: /<command>